import type { Company } from "@/types/interview"

export const companies: Company[] = [
  {
    id: "google",
    name: "Google",
    logo: "🔍",
    description: "Search giant with rigorous interview process",
    roles: [
      {
        id: "sde1",
        name: "Software Engineer - Level 3 (SDE1)",
        level: "junior",
        description: "Entry-level software engineer position",
        rounds: [
          {
            id: "round1",
            name: "Phone Screen",
            type: "call",
            duration: 45,
            description: "Initial screening call with recruiter",
            tips: ["Be clear about your background", "Ask about the role and team", "Prepare 2-3 questions"],
          },
          {
            id: "round2",
            name: "Coding Round 1",
            type: "coding",
            duration: 60,
            description: "Live coding interview on medium-level problems",
            tips: ["Think out loud", "Ask clarifying questions", "Optimize after getting a working solution"],
          },
          {
            id: "round3",
            name: "Coding Round 2",
            type: "coding",
            duration: 60,
            description: "Another coding round, possibly harder",
            tips: ["Practice LeetCode medium problems", "Know your data structures", "Time management is key"],
          },
          {
            id: "round4",
            name: "System Design",
            type: "system-design",
            duration: 45,
            description: "Design a scalable system",
            tips: ["Start with requirements", "Draw diagrams", "Discuss trade-offs"],
          },
          {
            id: "round5",
            name: "Behavioral Round",
            type: "hr",
            duration: 30,
            description: "HR and behavioral questions",
            tips: ["Use STAR method", "Be authentic", "Ask about team culture"],
          },
        ],
        totalDuration: 240,
      },
      {
        id: "sde2",
        name: "Software Engineer - Level 4 (SDE2)",
        level: "mid",
        description: "Mid-level software engineer position",
        rounds: [
          {
            id: "round1",
            name: "Phone Screen",
            type: "call",
            duration: 45,
            description: "Initial screening call with recruiter",
            tips: ["Highlight relevant experience", "Be ready to discuss projects"],
          },
          {
            id: "round2",
            name: "Coding Round 1",
            type: "coding",
            duration: 75,
            description: "Hard-level coding problems",
            tips: ["Optimize for time and space", "Consider edge cases", "Write clean code"],
          },
          {
            id: "round3",
            name: "Coding Round 2",
            type: "coding",
            duration: 75,
            description: "Another hard coding round",
            tips: ["Practice hard problems", "Know advanced data structures"],
          },
          {
            id: "round4",
            name: "System Design",
            type: "system-design",
            duration: 60,
            description: "Complex system design",
            tips: ["Think about scale", "Discuss databases", "Consider failure scenarios"],
          },
          {
            id: "round5",
            name: "Behavioral Round",
            type: "hr",
            duration: 30,
            description: "Leadership and behavioral questions",
            tips: ["Discuss leadership experience", "Show growth mindset"],
          },
        ],
        totalDuration: 285,
      },
    ],
  },
  {
    id: "microsoft",
    name: "Microsoft",
    logo: "⊞",
    description: "Tech leader with comprehensive interview rounds",
    roles: [
      {
        id: "sde1",
        name: "Software Engineer - Level 60 (SDE1)",
        level: "junior",
        description: "Entry-level software engineer",
        rounds: [
          {
            id: "round1",
            name: "Phone Screen",
            type: "call",
            duration: 45,
            description: "Initial phone screening",
            tips: ["Be enthusiastic", "Ask clarifying questions"],
          },
          {
            id: "round2",
            name: "Coding Round 1",
            type: "coding",
            duration: 60,
            description: "Medium-level coding problems",
            tips: ["Practice arrays and strings", "Think of multiple approaches"],
          },
          {
            id: "round3",
            name: "Coding Round 2",
            type: "coding",
            duration: 60,
            description: "Another coding round",
            tips: ["Be consistent", "Communicate clearly"],
          },
          {
            id: "round4",
            name: "System Design",
            type: "system-design",
            duration: 45,
            description: "Basic system design",
            tips: ["Start simple", "Scale gradually"],
          },
          {
            id: "round5",
            name: "Behavioral",
            type: "hr",
            duration: 30,
            description: "Behavioral and cultural fit",
            tips: ["Be genuine", "Show passion for technology"],
          },
        ],
        totalDuration: 240,
      },
    ],
  },
  {
    id: "amazon",
    name: "Amazon",
    logo: "🔶",
    description: "E-commerce giant with leadership principles focus",
    roles: [
      {
        id: "sde1",
        name: "Software Development Engineer - Level 4",
        level: "junior",
        description: "Entry-level SDE at Amazon",
        rounds: [
          {
            id: "round1",
            name: "Phone Screen",
            type: "call",
            duration: 45,
            description: "Initial screening",
            tips: ["Know Amazon leadership principles"],
          },
          {
            id: "round2",
            name: "Coding Round 1",
            type: "coding",
            duration: 60,
            description: "Medium coding problems",
            tips: ["Practice on LeetCode", "Think about edge cases"],
          },
          {
            id: "round3",
            name: "Coding Round 2",
            type: "coding",
            duration: 60,
            description: "Another coding round",
            tips: ["Be methodical", "Explain your approach"],
          },
          {
            id: "round4",
            name: "Bar Raiser Round",
            type: "system-design",
            duration: 60,
            description: "Senior engineer evaluating you",
            tips: ["Show depth of knowledge", "Ask good questions"],
          },
          {
            id: "round5",
            name: "Behavioral",
            type: "hr",
            duration: 30,
            description: "Leadership principles discussion",
            tips: ["Use STAR method", "Align with LP"],
          },
        ],
        totalDuration: 255,
      },
    ],
  },
  {
    id: "meta",
    name: "Meta",
    logo: "f",
    description: "Social media platform with focus on scale",
    roles: [
      {
        id: "sde1",
        name: "Software Engineer - E3",
        level: "junior",
        description: "Entry-level engineer at Meta",
        rounds: [
          {
            id: "round1",
            name: "Phone Screen",
            type: "call",
            duration: 45,
            description: "Initial call",
            tips: ["Be ready to discuss projects"],
          },
          {
            id: "round2",
            name: "Coding Round 1",
            type: "coding",
            duration: 60,
            description: "Medium problems",
            tips: ["Focus on correctness first"],
          },
          {
            id: "round3",
            name: "Coding Round 2",
            type: "coding",
            duration: 60,
            description: "Another round",
            tips: ["Optimize your solution"],
          },
          {
            id: "round4",
            name: "System Design",
            type: "system-design",
            duration: 45,
            description: "Design at scale",
            tips: ["Think about millions of users"],
          },
          {
            id: "round5",
            name: "Behavioral",
            type: "hr",
            duration: 30,
            description: "Culture and values",
            tips: ["Show passion", "Be authentic"],
          },
        ],
        totalDuration: 240,
      },
    ],
  },
]

export const publicInterviews: any[] = [
  {
    id: "pub1",
    companyId: "google",
    roleId: "sde1",
    userId: "user1",
    userName: "Rishabh",
    userSchool: "IIT Delhi",
    scores: {
      round1: 85,
      round2: 78,
      round3: 82,
      round4: 75,
      round5: 88,
    },
    overallScore: 81.6,
    feedback: "Great problem-solving skills. Could improve on system design.",
    createdAt: new Date("2024-10-15"),
    isPublic: true,
  },
  {
    id: "pub2",
    companyId: "google",
    roleId: "sde1",
    userId: "user2",
    userName: "Neha",
    userSchool: "PES Bengaluru",
    scores: {
      round1: 90,
      round2: 85,
      round3: 88,
      round4: 82,
      round5: 92,
    },
    overallScore: 87.4,
    feedback: "Excellent communication and coding skills.",
    createdAt: new Date("2024-10-10"),
    isPublic: true,
  },
  {
    id: "pub3",
    companyId: "google",
    roleId: "sde1",
    userId: "user3",
    userName: "Ankit",
    userSchool: "NIT Trichy",
    scores: {
      round1: 72,
      round2: 68,
      round3: 75,
      round4: 70,
      round5: 80,
    },
    overallScore: 73,
    feedback: "Good effort. Practice more on DSA problems.",
    createdAt: new Date("2024-10-05"),
    isPublic: true,
  },
  {
    id: "pub4",
    companyId: "microsoft",
    roleId: "sde1",
    userId: "user4",
    userName: "Priya",
    userSchool: "BITS Pilani",
    scores: {
      round1: 88,
      round2: 82,
      round3: 85,
      round4: 80,
      round5: 90,
    },
    overallScore: 85,
    feedback: "Strong technical foundation. Great communication.",
    createdAt: new Date("2024-10-18"),
    isPublic: true,
  },
  {
    id: "pub5",
    companyId: "amazon",
    roleId: "sde1",
    userId: "user5",
    userName: "Vikram",
    userSchool: "IIT Bombay",
    scores: {
      round1: 92,
      round2: 88,
      round3: 90,
      round4: 85,
      round5: 94,
    },
    overallScore: 89.8,
    feedback: "Exceptional performance. Leadership principles well understood.",
    createdAt: new Date("2024-10-20"),
    isPublic: true,
  },
  {
    id: "pub6",
    companyId: "meta",
    roleId: "sde1",
    userId: "user6",
    userName: "Shreya",
    userSchool: "NIT Bangalore",
    scores: {
      round1: 80,
      round2: 75,
      round3: 78,
      round4: 72,
      round5: 85,
    },
    overallScore: 78,
    feedback: "Good fundamentals. Work on optimization.",
    createdAt: new Date("2024-10-12"),
    isPublic: true,
  },
  {
    id: "pub7",
    companyId: "google",
    roleId: "sde2",
    userId: "user7",
    userName: "Arjun",
    userSchool: "IIT Madras",
    scores: {
      round1: 86,
      round2: 84,
      round3: 82,
      round4: 88,
      round5: 90,
    },
    overallScore: 86,
    feedback: "Excellent system design thinking. Ready for mid-level role.",
    createdAt: new Date("2024-10-08"),
    isPublic: true,
  },
  {
    id: "pub8",
    companyId: "microsoft",
    roleId: "sde1",
    userId: "user8",
    userName: "Divya",
    userSchool: "IIIT Hyderabad",
    scores: {
      round1: 75,
      round2: 70,
      round3: 73,
      round4: 68,
      round5: 80,
    },
    overallScore: 73.2,
    feedback: "Decent attempt. Practice more coding problems.",
    createdAt: new Date("2024-10-03"),
    isPublic: true,
  },
  {
    id: "pub9",
    companyId: "amazon",
    roleId: "sde1",
    userId: "user9",
    userName: "Rohan",
    userSchool: "IIT Delhi",
    scores: {
      round1: 84,
      round2: 80,
      round3: 82,
      round4: 78,
      round5: 88,
    },
    overallScore: 82.4,
    feedback: "Strong candidate. Good problem-solving approach.",
    createdAt: new Date("2024-10-14"),
    isPublic: true,
  },
  {
    id: "pub10",
    companyId: "meta",
    roleId: "sde1",
    userId: "user10",
    userName: "Aisha",
    userSchool: "BITS Goa",
    scores: {
      round1: 89,
      round2: 86,
      round3: 88,
      round4: 84,
      round5: 91,
    },
    overallScore: 87.6,
    feedback: "Excellent all-around performance. Ready to join.",
    createdAt: new Date("2024-10-17"),
    isPublic: true,
  },
]