
import { Label } from "@repo/ui/components/ui/label";
import { Button } from "@repo/ui/components/ui/button";
import { Input } from "@repo/ui/components/ui/input";
import { Textarea } from "@repo/ui/components/ui/textarea";
import { Plus, Trash2, Code2 } from "lucide-react";
import CodeEditor from "@/components/main/code-editor";
import { StepBlock } from "./types";
import { MarkdownRenderer } from "@/components/common/markdown-renderer";

export function CodeBlockEditor({ block, updateBlock, previewMode }: { block: StepBlock; updateBlock: (id: string, u: Partial<StepBlock>) => void; previewMode: boolean }) {
    const addCB = () => {
        const cbs = [...block.codeBlocks, { order: block.codeBlocks.length, title: "", language: "javascript", code: "", explanation: "", isRunnable: false }];
        updateBlock(block.localId, { codeBlocks: cbs });
    };

    return (
        <div className="space-y-4">
            <div className="space-y-3">
                <div className="flex items-center justify-between">
                    <Label className="text-xs font-medium text-muted-foreground">Code Blocks</Label>
                    <Button variant="outline" size="sm" onClick={addCB} className="h-7 text-xs">
                        <Plus className="w-3 h-3 mr-1" /> Add Code Block
                    </Button>
                </div>
                {
                    block.codeBlocks.length === 0 && (
                        <div className="text-center p-8 border-2 border-dashed border-neutral-200 dark:border-neutral-800 rounded-xl text-muted-foreground">
                            <Code2 className="w-6 h-6 mx-auto mb-2 opacity-30" />
                            <p className="text-xs">No code blocks yet. Use AI to generate or add manually.</p>
                        </div>
                    )
                }
                {
                    block.codeBlocks.map((cb, i) => (
                        <div key={i} className="border rounded-xl overflow-hidden bg-neutral-900 text-white shadow-sm">
                            <div className="flex items-center justify-between px-3 py-2 bg-neutral-800 border-b border-neutral-700">
                                <Input value={cb.title} onChange={e => { const cbs = [...block.codeBlocks]; cbs[i] = { ...cb, title: e.target.value }; updateBlock(block.localId, { codeBlocks: cbs }); }}
                                    placeholder="Code block title" className="bg-transparent border-0 text-white text-xs h-7 focus-visible:ring-0 w-48" />
                                <Button variant="ghost" size="sm" className="h-6 w-6 p-0 text-neutral-400 hover:text-red-400" onClick={() => { const cbs = block.codeBlocks.filter((_, j) => j !== i); updateBlock(block.localId, { codeBlocks: cbs }); }}>
                                    <Trash2 className="w-3 h-3" />
                                </Button>
                            </div>
                            <CodeEditor code={cb.code} language={cb.language} height="200px" showRunButton={false} showLanguageSelector
                                onChange={code => { const cbs = [...block.codeBlocks]; cbs[i] = { ...cb, code }; updateBlock(block.localId, { codeBlocks: cbs }); }}
                                onLanguageChange={lang => { const cbs = [...block.codeBlocks]; cbs[i] = { ...cb, language: lang }; updateBlock(block.localId, { codeBlocks: cbs }); }} />
                            <div className="bg-white dark:bg-neutral-950 border-t border-neutral-200 dark:border-neutral-800 p-3">
                                <Textarea value={cb.explanation}
                                    onChange={e => { const cbs = [...block.codeBlocks]; cbs[i] = { ...cb, explanation: e.target.value }; updateBlock(block.localId, { codeBlocks: cbs }); }}
                                    placeholder="Explanation for this code block..."
                                    className="text-sm min-h-[60px] border-0 bg-transparent focus-visible:ring-0 p-0 resize-none" />
                            </div>
                        </div>
                    ))
                }
            </div>
            <div className="space-y-2">
                <Label className="text-xs font-medium text-muted-foreground">Step Explanation</Label>
                {
                    previewMode ? (
                        <div className="p-4 border rounded-xl bg-white dark:bg-neutral-900 max-w-none min-h-[120px] text-sm">
                            <MarkdownRenderer content={block.content || "*No explanation yet.*"} />
                        </div>
                    ) : (
                        <Textarea value={block.content} onChange={e => updateBlock(block.localId, { content: e.target.value })}
                            placeholder="Explanation generated by AI will appear here, you can also edit..."
                            rows={5} className="text-sm" />
                    )
                }
            </div>
        </div>
    );
}
