
import { Label } from "@repo/ui/components/ui/label";
import { Textarea } from "@repo/ui/components/ui/textarea";
import { MarkdownRenderer } from "@/components/common/markdown-renderer";
import { StepBlock } from "./types";

export function ContentEditor({ block, updateBlock, previewMode }: { block: StepBlock; updateBlock: (id: string, u: Partial<StepBlock>) => void; previewMode: boolean }) {
    return (
        <div className="space-y-2">
            <Label className="text-xs font-medium text-muted-foreground">Content (Markdown)</Label>
            {
                previewMode ? (
                    <div className="p-6 border rounded-xl bg-white dark:bg-neutral-900 max-w-none min-h-[300px]">
                        <MarkdownRenderer content={block.content || "*No content yet. Use the AI generator above or switch to Edit mode.*"} />
                    </div>
                ) : (
                    <Textarea value={block.content} onChange={e => updateBlock(block.localId, { content: e.target.value })}
                        placeholder="Content will be generated by AI, or you can write/edit markdown here..."
                        rows={16} className="font-mono text-sm" />
                )
            }
        </div>
    );
}